language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

env:
  - ELM_VERSION=0.19.0

cache:
  directories: # so subsequent builds run faster
    - $HOME/.elm
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249


install: # install specific versions of elm & elm-test
  - npm install -g elm@$ELM_VERSION

script:
  - elm-make src/Main.elm